spring:
  application:
    name: spring-plus
  datasource:
    url: jdbc:mysql://localhost:3306/spring-plus?rewriteBatchedStatements=true
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
    open-in-view: false

  batch.job.enabled: false

jwt:
  secret:
    key: "IGVy2RrhXr5jQv3ZtYBWzKoW6kQgJpjrB50rQmU+4JPBa5zKT4Q1cOZu7blIEtYo1+93CEEMlA7ybK49w0tzqA=="

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: users-profile86
